# Use Node.js image
FROM node:18

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Copy frontend source code
COPY . .

# Expose the frontend port
EXPOSE 3000

# Start React app
CMD ["npm", "start"]
